name: Cargo Build & Test

on:
  pull_request:
  # push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: a.rs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo check
      - run: cargo fmt
      - run: cargo test --verbose
